### ISSUE TITLE
Unclear versions of dependencies

### ISSUE THREAD

**Issue by alstrup** [domschl/python-mchess#11]
Thibault discovered after some trial and error that you need:

pip3 install flask==1.1.4 flask-sockets==0.2.1.

**Comment by ornicar** [comment]
What you need imo is a `requirements.txt` file to specify the desired version of each dependency. I found these by trial and they seem to work, but they may not be optimal

**Comment by domschl** [comment]
You're of course right about a `requirements.txt`. The excuse is that this is far from even close to beta, and I haven't had time to update this recently. This being said, I just made a fresh install today, using simply latest versions of all modules:
```
Flask==2.0.1
Flask-Sockets==0.2.1
gevent==21.1.2
gevent-websocket==0.10.1
```
and had no problems on Python 3.9.5, Macbook M1. What kind of error did you encounter?
