### ISSUE TITLE
Menu Analyse Tool 1

### ISSUE THREAD

**Issue by ccanger** [domschl/python-mchess#4]
Das ist sehr  gut gemacht und praktisch ! Er zeigt nacheinander auf dem Brett die Züge an, welche auch bei der UCI Schnittstelle auf dem Terminal erscheinen. Die Zeit zwischen den Zügen ist ein wenig zu schnell, vielleicht doppelt so lange wäre gut, oder eine Einstellungsoption zur Zeit. Ich bin begeistert ! :-)

**Comment by domschl** [comment]
Laden Sie den letzten Update.

Beim Start wird in preferences.json eine neue Option geschrieben:

"ply_vis_delay": 80

Wenn Sie den Wert erhoehen, wird die Visualisierung der Zugfolge langsamer.

Viel Spass!
